services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: lista_ai_postgres
    environment:
      POSTGRES_DB: lista_ai_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: