spring:
  application:
    name: Lista AI

  datasource:
    url: jdbc:postgresql://localhost:5432/lista_ai_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  threads:
    virtual:
      enabled: true
